### ISSUE TITLE
`The method or operation is not implemented` while iterating children of physical folder `\Properties`

### ISSUE THREAD

**Issue by lsoft** [VsixCommunity/Community.VisualStudio.Toolkit#143]
I received this exception while iterating through .Net Framework Class Library project. One of the children of `\Properties` physical folder gives me the following error:

```csharp
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Community.VisualStudio.Toolkit.SolutionItem.GetFullPath()
   at Community.VisualStudio.Toolkit.SolutionItem..ctor(IVsHierarchyItem item, SolutionItemType type)
   at Community.VisualStudio.Toolkit.SolutionItem.FromHierarchyItem(IVsHierarchyItem item)
   at Community.VisualStudio.Toolkit.SolutionItem.<>c.<get_Children>b__20_0(IVsHierarchyItem t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
```

Exception code:

```csharp
        public static void FindFolders(
            this Community.VisualStudio.Toolkit.SolutionItem root,
            List<Community.VisualStudio.Toolkit.SolutionItem> folders
            )
        {
            if (root.Type == SolutionItemType.PhysicalFolder)
            {
                folders.Add(root);
            }

            foreach (var child in root.Children)
            {
                FindFolders(child, folders);
            }
        }

```

My task was to take all physical folders from concrete project. 

----

I noticed from VSSDK (not Community.VSSDK) that some project items raises an exception if you will ask for their path, so I switched to the following construction:

```csharp
        public static bool TryGetFileName(
            this ProjectItem prjItem,
            int index,
            out string? fileName
            )
        {
            try
            {
                fileName = prjItem.FileNames[(short)index];
                return true;
            }
            catch (ArgumentException)
            {
                fileName = null;
                return false;
            }
        }
```

May be the same problem occurs here....

Thanks!

**Comment by reduckted** [comment]
I can reproduce this, but (for me, at least) it's not the `Properties` folder that's causing the error. I'm using this solution structure:
![image](https://user-images.githubusercontent.com/10321525/129883339-34ad3ded-c557-4c89-a27d-1825c18eb617.png)

The `Properties` folder in this solution is a physical folder, so it's name can be retrieved successfully (this could be different for you). For me, the error is occurring on the `References` node of the `NetFxConsole` project, which is a "virtual folder".

I would have expected the same error on the `Dependencies` property of `ExtensionTester`, but surprisingly it's full path can be retrieved without error. It returns ">62" though, so I suspect we shouldn't be asking for it's full path anyway. Must be a difference between .NET Framework projects and CPS projects.

**Comment by lsoft** [comment]
workaround I found:

```csharp
        public static void FindFolders(
            this SolutionItem root,
            Dictionary<string, SolutionItem> folders
            )
        {
            if (root.Type == SolutionItemType.PhysicalFolder)
            {
                if (!string.IsNullOrEmpty(root.FullPath))
                {
                    folders[root.FullPath] = root;
                }
            }

            using var enumerator = root.Children.GetEnumerator();
            while (true)
            {
                try
                {
                    var r = enumerator.MoveNext();
                    if (!r)
                    {
                        break;
                    }
                }
                catch (NotImplementedException)
                {
                    //suppress it due to https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/143
                }

                var child = enumerator.Current;
                FindFolders(child, folders);
            }
        }
```
