### ISSUE TITLE
Rating prompt issue

### ISSUE THREAD

**Issue by ErikEJ** [VsixCommunity/Community.VisualStudio.Toolkit#281]
I have taken the code from MarkdownEditor2022 (beofore it was added here, which is great, and I will adopt) - but getting this error - what am I doing wrong?

FYI: I am using .16 lib version 16.0.406  and running against a VS 2022 experimental instance

```
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.Shell.InfoBarModel..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Shell.Interop.IVsInfoBarTextSpan>, System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Shell.Interop.IVsInfoBarActionItem>, Microsoft.VisualStudio.Imaging.Interop.ImageMoniker, Boolean)'.
   at BaseClasses.RatingPrompt.<PromptAsync>d__23.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at BaseClasses.RatingPrompt.PromptAsync()
   at BaseClasses.RatingPrompt.<IncrementAsync>d__22.MoveNext() in C:\Code\EFCorePowerTools\src\GUI\Shared\BaseClasses\RatingPrompt.cs:line 69<---

```

**Comment by madskristensen** [comment]
I'm seeing the same thing and I don't understand it. I'll replace the InfoBar with a custom dialog box instead, which will fix the issue. But it means that `InfoBarModel` is not compatible between VS 2019 and 2022, which is weird since it's not a service or COM interface

**Comment by madskristensen** [comment]
@jekelly It's strange that the constructor of `InfoBarModel` shows incompatibilities between VS 16.0 and 17.0 in similar ways the old COM services and interops do. It's a much newer class (14.0??)

**Comment by ErikEJ** [comment]
@madskristensen on another note:
I am watching all activity in this repo, but it was completely by chance that I noticed that RatingPrompt had been added. Is there a process gap somewhere?

**Comment by madskristensen** [comment]
Yes probably. As in, there is no process :)

**Comment by ErikEJ** [comment]
@madskristensen Any workarounds possible? or I must wait for a switch to a custom dialog?
