### ISSUE TITLE
"themes/themeresources.xaml is missing" error on 17.0.430

### ISSUE THREAD

**Issue by asaf92** [VsixCommunity/Community.VisualStudio.Toolkit#322]
On version 17.0.430, we get a `System.IO.IOException` during the `InitializeComponent` call on UserControls that use `toolkit:Themes.UseVsTheme="True"`. 

The exception says that `themes/themeresources.xaml` is missing.

[Reverting to 17.0.394 fixed it](https://github.com/snyk/snyk-visual-studio-plugin/pull/134).

Callstack:
```
System.Windows.Markup.XamlParseException: Initialization of 'Snyk.VisualStudio.Extension.Shared.UI.Tree.SnykFilterableTree' threw an exception. ---> System.IO.IOException: Cannot locate resource 'themes/themeresources.xaml'.
at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
at System.IO.Packaging.PackWebResponse.get_ContentType()
at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response)
at System.Windows.ResourceDictionary.set_Source(Uri value)
at Community.VisualStudio.Toolkit.Themes.MergeStyles(FrameworkElement element)
at Community.VisualStudio.Toolkit.Themes.OnElementInitialized(Object sender, EventArgs args)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at System.Windows.FrameworkElement.RaiseInitialized(EventPrivateKey key, EventArgs e)
at System.Windows.FrameworkElement.TryFireInitialized()
at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
```

**Comment by madskristensen** [comment]
@reduckted could this be related to your latest changes?

**Comment by reduckted** [comment]
Woah! That's really weird. When building using MSBuild, the resulting assembly contains the resources, but when building using `dotnet pack`, the resources are not included.

![image](https://user-images.githubusercontent.com/10321525/163655841-73654670-a001-45bf-ab6c-3ddac58d5cee.png)

**Comment by reduckted** [comment]
#323 should fix this. The projects needed to set `UseWPF` to true so that the XAML files were processed correctly when using the .NET SDK to build the assemblies.

**Comment by KC250330** [comment]
Question. I'm also seeing this issue. I see the PR has been merged to the main branch. When will a new build be pushed to nuget?

**Comment by HRussellZFAC023** [comment]
@KC250330 I am not sure if this helps you, but I was able to advance the nuget package for toolkit and that fixed the issue for me.
![image](https://user-images.githubusercontent.com/22746105/173195504-cfec9e3e-0947-4683-8be7-7e120d14e5e0.png)

**Comment by AlonAm** [comment]
> Question. I'm also seeing this issue. I see the PR has been merged to the main branch. When will a new build be pushed to nuget?
> 
> I tried to roll back to 17.0.394, however I'm also using the Community.VisualStudio.Toolkit.DependencyInjection frameworks and when I tried to roll them back a version I get all kind of issue with the DI Commands.

Adding a `ProvideBindingRedirection ` attribute can resolve the mismatch
```csharp
[assembly: ProvideBindingRedirection(AssemblyName = "Community.VisualStudio.Toolkit", OldVersionLowerBound = "17.0.430.0", OldVersionUpperBound = "17.0.475.0", NewVersion = "17.0.482.0")]
```
